### ISSUE TITLE
`go get` error

### ISSUE THREAD

**Issue by sklarsa** [aktau/gofinance#1]
Hey, I'm getting the following error when running `go get github.com/aktau/gofinance/gofinance`

```
package github.com/aktau/gofinance/gofinance: cannot find package "github.com/aktau/gofinance/gofinance" in any of:
	/usr/local/Cellar/go/1.7.1/libexec/src/github.com/aktau/gofinance/gofinance (from $GOROOT)
	/Users/steven/Go/src/github.com/aktau/gofinance/gofinance (from $GOPATH)
```
I'm a go noob but haven't encountered this error before when running `go get`.  Am I doing something wrong?

I'm running `go version go1.7.1 darwin/amd64`

Thanks!
Steve

**Comment by HT808s** [comment]
Hello @sklarsa,
This error is the result of outdated dependencies
I will try to continue the project 
If you'd like you can start having a look at my fork and review my PR !
https://github.com/HT808s/gofinance/pull/1

**Comment by sklarsa** [comment]
Outdated dependencies

**Comment by idanya** [comment]
I'm getting the same error. How did you fixed it?

**Comment by sklarsa** [comment]
This package uses an older version of go.  My fork of this repo should work for you.  Try `go get github.com/sklarsa/gofinance`
